[package]
name = "aero-acpi"
version = "0.1.0"
rust-version.workspace = true
edition = "2021"
publish = false

[dependencies]
aero-pci-routing = { path = "../aero-pci-routing" }

[dev-dependencies]
aero-devices = { path = "../devices" }
aero-pc-constants = { path = "../aero-pc-constants" }
aero-platform = { path = "../platform" }
tempfile = "3"
