[package]
name = "aero-net-backend"
version = "0.1.0"
rust-version.workspace = true
edition = "2021"
publish = false

[dependencies]
# `wasm` feature is enabled so the crate can support `SharedRingBuffer` on wasm32.
aero-ipc = { path = "../aero-ipc", features = ["wasm"] }
aero-l2-protocol = { path = "../aero-l2-protocol" }
